2017/07/31 09:38:19 [error] [exception.CDbException] [5.121.38.56] invalid data source name
2017/07/31 09:38:19 [error] [exception.CDbException] [5.121.38.56] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php:405
Stack trace:
#0 C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\mw\apps\common\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\mw\apps\common\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\mw\apps\common\components\managers\OptionsManager.php(164): CModule->__get('db')
#5 C:\xampp\htdocs\mw\apps\common\components\managers\OptionsManager.php(73): OptionsManager->loadCategory('system.common.s...')
#6 C:\xampp\htdocs\mw\apps\common\components\init\SystemInit.php(48): OptionsManager->get('system.common.s...')
#7 C:\xampp\htdocs\mw\apps\common\framework\base\CComponent.php(561): SystemInit->_runOnBeginRequest(Object(CEvent))
#8 C:\xampp\htdocs\mw\apps\common\framework\base\CApplication.php(212): CComponent->raiseEvent('onBeginRequest', Object(CEvent))
#9 C:\xampp\htdocs\mw\apps\common\framework\base\CApplication.php(183): CApplication->onBeginRequest(Object(CEvent))
#10 C:\xampp\htdocs\mw\apps\init.php(233): CApplication->run()
#11 C:\xampp\htdocs\mw\index.php(18): require_once('C:\\xampp\\htdocs...')
#12 {main}
REQUEST_URI=/mw/
---
2017/07/31 09:38:19 [error] [exception.CDbException] [5.121.38.56] invalid data source name
2017/07/31 09:38:21 [error] [exception.CDbException] [5.121.38.56] invalid data source name
2017/07/31 09:38:21 [error] [exception.CDbException] [5.121.38.56] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php:405
Stack trace:
#0 C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\mw\apps\common\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\mw\apps\common\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\mw\apps\common\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\mw\apps\common\components\managers\OptionsManager.php(164): CModule->__get('db')
#5 C:\xampp\htdocs\mw\apps\common\components\managers\OptionsManager.php(73): OptionsManager->loadCategory('system.common.s...')
#6 C:\xampp\htdocs\mw\apps\common\components\init\SystemInit.php(48): OptionsManager->get('system.common.s...')
#7 C:\xampp\htdocs\mw\apps\common\framework\base\CComponent.php(561): SystemInit->_runOnBeginRequest(Object(CEvent))
#8 C:\xampp\htdocs\mw\apps\common\framework\base\CApplication.php(212): CComponent->raiseEvent('onBeginRequest', Object(CEvent))
#9 C:\xampp\htdocs\mw\apps\common\framework\base\CApplication.php(183): CApplication->onBeginRequest(Object(CEvent))
#10 C:\xampp\htdocs\mw\apps\init.php(233): CApplication->run()
#11 C:\xampp\htdocs\mw\index.php(18): require_once('C:\\xampp\\htdocs...')
#12 {main}
REQUEST_URI=/mw/
HTTP_REFERER=http://192.30.85.117/mw/
---
2017/07/31 09:38:21 [error] [exception.CDbException] [5.121.38.56] invalid data source name
